twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    # en  cas ou le theme sera appliqué sur tous les vues twig , sinon {% form_theme NomDeForm 'bootstrap_4_layout.html.twig' %}
    # directement sur la vue 
    form_themes: ['bootstrap_4_layout.html.twig']

